---
title: "Case Study2"
author: "Michalel Toolin, JaimeVillanueva,Venkat Kasarla"
date: "11/23/2017"  
output: 
    html_document:
          keep_md: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library("readxl")
library(tidyr)
library(dplyr)
library(ggplot2)
```

```{r readExcel}
rawdata.xls <- '../data/CaseStudy2-data.xlsx'
rawdata.csv <- '../data/original.csv'
refine <- read_excel(rawdata.xls,1)
refine %>% data.table::fwrite(rawdata.csv)
dframe <- read.csv(rawdata.csv)
rawdata <- dframe
```

<br>

```{r genderAttritionSummary}
ggplot(rawdata,aes(Gender,fill=Attrition)) + geom_bar(position="dodge")
ggplot(rawdata,aes(Gender, group=Attrition))+
  geom_bar(aes(y=..prop..,fill=factor(..x..)),stat="count")+
  geom_text(aes(label=scales::percent(..prop..),
                y=..prop..),stat="count",vjust=-.5)+
  labs(y="Percent")+
  scale_y_continuous(labels=scales::percent)+
  theme(axis.text.x = element_text(angle=0, hjust=1),legend.position="none")+
  facet_grid(~Attrition)
```

<br>

```{r hourlyRateAttritionSummary}
ggplot(rawdata,aes(HourlyRate,fill=Attrition)) + geom_bar(position="dodge")
ggplot(rawdata,aes(HourlyRate, group=Attrition))+
  geom_bar(aes(y=..prop..,fill=factor(..x..)),stat="count")+
  geom_text(aes(label=scales::percent(..prop..),
                y=..prop..),stat="count",vjust=-.5,check_overlap = TRUE)+
  labs(y="Percent",fill="HourlyRate")+
  scale_y_continuous(labels=scales::percent)+
  facet_grid(~Attrition)
```

<br>

```{r jobInvolvementAttritionsummary}
ggplot(rawdata,aes(JobInvolvement,fill=Attrition)) + geom_bar(position="dodge")
rawdata$JobInvolvement <- factor(rawdata$JobInvolvement,levels = c(1, 2, 3,4), labels = c("Low","Medium","High","Very High"))
ggplot(rawdata,aes(JobInvolvement, group=Attrition,fill=JobInvolvement))+
  geom_bar(aes(y=..prop..,fill=factor(..x..)),stat="count")+
  geom_text(aes(label=scales::percent(..prop..),
                y=..prop..),stat="count",vjust=-.5)+
  labs(y="Percent")+
  scale_y_continuous(labels=scales::percent)+
  theme(axis.text.x = element_text(angle=60, hjust=1),legend.position="none")+
  facet_grid(~Attrition)
```

<br>

```{r joblevelAttritionSummary}
ggplot(rawdata,aes(JobLevel,fill=Attrition)) + geom_bar(position="dodge")
ggplot(rawdata,aes(JobLevel, group=Attrition))+
  geom_bar(aes(y=..prop..,fill=factor(..x..)),stat="count")+
  geom_text(aes(label=scales::percent(..prop..),
                y=..prop..),stat="count",vjust=-.5)+
  labs(y="Percent")+
  scale_y_continuous(labels=scales::percent)+
  theme(axis.text.x = element_text(angle=0, hjust=1),legend.position="none")+
  facet_grid(~Attrition)
```

<br>

```{r jobRoleAttritionSummary}
ggplot(rawdata,aes(JobRole,fill=Attrition)) + geom_bar(position="dodge")
ggplot(rawdata,aes(JobRole, group=Attrition))+
  geom_bar(aes(y=..prop..,fill=factor(..x..)),stat="count")+
  geom_text(aes(label=scales::percent(..prop..),
                y=..prop..),stat="count",vjust=-.5)+
  labs(y="Percent")+
  scale_y_continuous(labels=scales::percent)+
  theme(axis.text.x = element_text(angle=60, hjust=1),legend.position="none")+
  facet_grid(~Attrition)
```

<br>

```{r jobsatisfactionAttritionSummary}
ggplot(rawdata,aes(JobSatisfaction,fill=Attrition)) + geom_bar(position="dodge")
rawdata$JobSatisfaction <- factor(rawdata$JobSatisfaction,levels = c(1, 2, 3,4), labels = c("Low","Medium","High","Very High"))
ggplot(rawdata,aes(JobSatisfaction, group=Attrition))+
  geom_bar(aes(y=..prop..,fill=factor(..x..)),stat="count")+
  geom_text(aes(label=scales::percent(..prop..),
                y=..prop..),stat="count",vjust=-.5)+
  labs(y="Percent",fill="JobSatisfaction")+
  scale_y_continuous(labels=scales::percent)+
  theme(axis.text.x = element_text(angle=60, hjust=1),legend.position="none")+
  facet_grid(~Attrition)
```

<br>

```{r maritalStatusAttritionSummary}
ggplot(rawdata,aes(MaritalStatus,fill=Attrition)) + geom_bar(position="dodge")
ggplot(rawdata,aes(MaritalStatus, group=Attrition))+
  geom_bar(aes(y=..prop..,fill=factor(..x..)),stat="count")+
  geom_text(aes(label=scales::percent(..prop..),
                y=..prop..),stat="count",vjust=-.5)+
  labs(y="Percent")+
  scale_y_continuous(labels=scales::percent)+
  theme(axis.text.x = element_text(angle=0, hjust=1),legend.position="none")+
  facet_grid(~Attrition)
```

<br>

```{r monthlyRateAttrition}
f <- function(x) {
  r <- quantile(x, probs = c(0.05, 0.25, 0.5, 0.75, 0.95))
  names(r) <- c("ymin", "lower", "middle", "upper", "ymax")
  r
}

ggplot(rawdata, aes(Attrition, MonthlyRate)) + stat_summary(fun.data = f, geom="boxplot")

# define outlier as you want 0-25%  and 75-100% outliers   
o <- function(x) {
  subset(x, x < quantile(x)[2] | quantile(x)[4] < x)
}

#Monthly Rate
ggplot(rawdata, aes(Attrition, MonthlyRate)) + 
  stat_summary(fun.data=f, geom="boxplot") + 
  stat_summary(fun.y = o, geom="point")

#Hourly Rate
ggplot(rawdata, aes(Attrition, HourlyRate)) + 
  stat_summary(fun.data=f, geom="boxplot") + 
  stat_summary(fun.y = o, geom="point")

```

<br>

```{r monthlyIncomeAttritionSummary}
#Monthly Income
ggplot(rawdata, aes(Attrition, MonthlyIncome)) + 
  stat_summary(fun.data=f, geom="boxplot") + 
  stat_summary(fun.y = o, geom="point")

quantie.val <- quantile(rawdata$MonthlyIncome)
rawdata$IncomeGroup[rawdata$MonthlyIncome < quantie.val[1]] <- "Low"
rawdata$IncomeGroup[rawdata$MonthlyIncome >= quantie.val[1] & rawdata$MonthlyIncome < quantie.val[2]] <- "Low Medium"
rawdata$IncomeGroup[rawdata$MonthlyIncome >= quantie.val[2] & rawdata$MonthlyIncome < quantie.val[3]] <- "Medium"
rawdata$IncomeGroup[rawdata$MonthlyIncome >= quantie.val[3] & rawdata$MonthlyIncome < quantie.val[4]] <- "Medium High"
rawdata$IncomeGroup[rawdata$MonthlyIncome >= quantie.val[4] & rawdata$MonthlyIncome < quantie.val[5]] <- "High"

ggplot(rawdata,aes(IncomeGroup, group=Attrition))+
  geom_bar(aes(y=..prop..,fill=factor(..x..)),stat="count")+
  geom_text(aes(label=scales::percent(..prop..),
                y=..prop..),stat="count",vjust=-.5)+
  labs(y="Percent")+
  scale_y_continuous(labels=scales::percent)+
  theme(axis.text.x = element_text(angle=60, hjust=1),legend.position="none")+
  facet_grid(~Attrition)

```

<br>

```{r numberCompaniesWorkedAttritionSummary}
ggplot(rawdata,aes(NumCompaniesWorked,fill=Attrition)) + geom_bar(position="dodge")
ggplot(rawdata,aes(NumCompaniesWorked, group=Attrition))+
  geom_bar(aes(y=..prop..,fill=factor(..x..)),stat="count")+
  geom_text(aes(label=scales::percent(..prop..),
                y=..prop..),stat="count",vjust=-.5)+
  labs(y="Percent")+
  scale_y_continuous(labels=scales::percent)+
   theme(axis.text.x = element_text(angle=0, hjust=1),legend.position="none")+
  facet_grid(~Attrition)
```

<br>

```{r Age18AttritionSummary}
ggplot(rawdata,aes(Over18,fill=Attrition)) + geom_bar(position="dodge")
ggplot(rawdata,aes(Over18, group=Attrition))+
  geom_bar(aes(y=..prop..,fill=factor(..x..)),stat="count")+
  geom_text(aes(label=scales::percent(..prop..),
                y=..prop..),stat="count",vjust=-.5)+
  labs(y="Percent",fill="Over18")+
  scale_y_continuous(labels=scales::percent)+
  facet_grid(~Attrition)
```

<br>


